### ISSUE TITLE
Convert UIActivityIndicatorViewStyleGray to UIActivityIndicatorViewStyleMedium

### ISSUE THREAD

**Issue by haarj** [BeatsKitano/KafkaRefresh#75]
Is it possible to convert all native UIActivityIndicatorView styles to UIActivityIndicatorViewStyleMedium to support iOS 13+ light/dark modes. Overriding the "color" property doesn't seem to change the color when the style is UIActivityIndicatorViewStyleGray.

Thank you!

**Comment by BeatsKitano** [comment]
🚀  KafkaRefresh (1.6.0) successfully published
 📅  April 14th, 15:46
 🌎  https://cocoapods.org/pods/KafkaRefresh
 👍  Tell your friends!

**Comment by haarj** [comment]
Omg you're amazing!
