### ISSUE TITLE
A phenomenon that UIScrollView contentInset falls into an infinite loop.

### ISSUE THREAD

**Issue by HyunjoonKo** [BeatsKitano/KafkaRefresh#76]
Under the following conditions, the phenomenon unconditionally occurs.

1. iOS 16.4 or higher.
2. Xcode 14.3 or higher.
3. On iPhone 14 Pro
4. In case of using contentInset separately for UIScrollView.

`setInsetTop:` in `KafkaCategories.m` will be called indefinitely.
As you can see from the stack trace in the screenshot, the key-value observer is still being called. The reason is that the tiny decimal place of the `inset.top` variable keeps changing.

<img width="1178" alt="screenshot" src="https://github.com/BeatsKitano/KafkaRefresh/assets/3861180/919a948c-e107-4513-9542-8312797001d9">

This can be easily fixed with the following code:
```
- (void)setInsetTop:(CGFloat)insetTop{
      UIEdgeInsets inset = self.contentInset;
      inset.top = insetTop;
      if (@available(iOS 11.0, *)) {
            inset.top -= (self.adjustedContentInset.top - self.contentInset.top);
      }
      CGFloat top = self.contentInset.top;
      if (round(top) != round(inset.top)) {
            self.contentInset = inset;
      }
      // top = 97.809374999999989
      // inset.top = 97.809374999999979
}
```

**Comment by BeatsKitano** [comment]
KafkaRefresh (1.7.0) successfully published. Fixed #76

Thanks for your issure
